"""SQLAlchemy ORM model for an individual flashcard with a question and answer."""
from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING, List, Optional

from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, String, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.db_setup import Base

if TYPE_CHECKING:
    from app.models.flashcard_deck import FlashcardDeck
    from app.models.flashcard_reviews import FlashcardReview
    from app.models.document import Document
    from app.models.session_topic import SessionTopic
    from app.models.document_chunk import DocumentChunk


class Flashcard(Base):
    """
    Represents a single prompt/response learning item.
    Supports spaced repetition tracking (SM-2 or similar algorithms).
    """
    __tablename__ = "flashcards"

    # Flashcards MUST belong to a deck
    deck_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("flashcard_decks.id", ondelete="CASCADE"), nullable=False, index=True
    )
    
    # Optional provenance: Where did this card come from?
    source_document_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        ForeignKey("documents.id", ondelete="SET NULL"), nullable=True, index=True
    )
    source_topic_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        ForeignKey("session_topics.id", ondelete="SET NULL"), nullable=True, index=True
    )
    source_chunk_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        ForeignKey("document_chunks.id", ondelete="SET NULL"), nullable=True
    )

    # Core card content
    front_content: Mapped[str] = mapped_column(String, nullable=False)
    back_content: Mapped[str] = mapped_column(String, nullable=False)
    
    # E.g., 'text', 'markdown', 'html', or 'image_url' to dictate frontend rendering
    front_content_type: Mapped[str] = mapped_column(String, nullable=False, default="text")
    back_content_type: Mapped[str] = mapped_column(String, nullable=False, default="text")
    
    # Additional context revealed on request or after failing
    hint: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    explanation: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    
    # General difficulty rating (1-5), distinct from dynamic SRS intervals
    difficulty: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    
    # For rigid sequence decks
    card_order: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    
    # Flags if this was auto-generated by the backend LLM tool
    ai_generated: Mapped[bool] = mapped_column(Boolean, default=False)

    # --- Spaced Repetition System (SRS) fields ---
    # Current wait time until the next review
    interval_days: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    # Number of consecutive successful recalls
    repetitions: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    # Timestamp indicating when the card is "due" again
    next_review_date: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    last_reviewed_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)

    # Statistics over the lifetime of the card
    total_reviews: Mapped[int] = mapped_column(Integer, default=0)
    successful_reviews: Mapped[int] = mapped_column(Integer, default=0)
    
    # True if the user knows this card perfectly and it rarely needs review
    is_mastered: Mapped[bool] = mapped_column(Boolean, default=False)
    is_public: Mapped[bool] = mapped_column(Boolean, default=False)
    is_archived: Mapped[bool] = mapped_column(Boolean, default=False)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )

    deck: Mapped["FlashcardDeck"] = relationship(
        "FlashcardDeck", back_populates="flashcards", lazy="selectin"
    )
    source_document: Mapped[Optional["Document"]] = relationship("Document", lazy="selectin")
    source_topic: Mapped[Optional["SessionTopic"]] = relationship("SessionTopic", lazy="selectin")
    source_chunk: Mapped[Optional["DocumentChunk"]] = relationship("DocumentChunk", lazy="noload")
    reviews: Mapped[List["FlashcardReview"]] = relationship(
        "FlashcardReview", back_populates="flashcard", cascade="all, delete-orphan", lazy="noload"
    )
