"""SQLAlchemy ORM model for small, session-scoped goals set during a study session."""
from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING, Optional

from sqlalchemy import DateTime, ForeignKey, Integer, SmallInteger, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.db_setup import Base

if TYPE_CHECKING:
    from app.models.study_session import StudySession


class MicroGoal(Base):
    """
    Actionable, granular step within a study session.
    Generated by AI after the session goal is confirmed, or created manually by the user.
    These are the checkboxes the user ticks off during the session.
    """
    __tablename__ = "micro_goals"

    session_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("study_sessions.id", ondelete="CASCADE"), nullable=False, index=True
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )

    title: Mapped[str] = mapped_column(String, nullable=False) # e.g., "Read Chapter 4"
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    
    # Provenance tracking: 'ai' if suggested by the agent, 'user' if manually added
    source: Mapped[str] = mapped_column(String, nullable=False, default="ai")
    
    # Lifecycle: pending | in_progress | completed | skipped
    status: Mapped[str] = mapped_column(String, nullable=False, default="pending")
    
    # Determines display order in the UI checklist
    order_index: Mapped[int] = mapped_column(SmallInteger, nullable=False, default=0)
    
    # Expected time to complete this specific micro-task
    estimated_minutes: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)

    completed_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )

    session: Mapped["StudySession"] = relationship(
        "StudySession", back_populates="micro_goals", lazy="selectin"
    )
