"""SQLAlchemy ORM model for a named set of quiz questions within a session."""
from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING, List, Optional

from sqlalchemy import DateTime, ForeignKey, Integer, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.db_setup import Base

if TYPE_CHECKING:
    from app.models.study_session import StudySession
    from app.models.document import Document
    from app.models.user import User
    from app.models.quiz_question import QuizQuestion
    from app.models.quiz_attempt import QuizAttempt


class QuizSet(Base):
    """
    A collection of quiz questions, either generated by the AI from a Document,
    or manually created by a user. Users can take a QuizSet multiple times (as QuizAttempts).
    """
    __tablename__ = "quiz_sets"

    session_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("study_sessions.id", ondelete="CASCADE"), nullable=False, index=True
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    # The source material from which the AI generated these questions (optional)
    document_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        ForeignKey("documents.id", ondelete="SET NULL"), nullable=True
    )

    title: Mapped[str] = mapped_column(String, nullable=False)
    
    # Provenance: ai | user
    source: Mapped[str] = mapped_column(String, nullable=False, default="ai")
    
    # Lifecycle: draft | ready | archived
    status: Mapped[str] = mapped_column(String, nullable=False, default="ready")
    
    # Denormalized count of attached QuizQuestions. Updated when questions are added/removed.
    question_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    ai_prompt_used: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    session: Mapped["StudySession"] = relationship(
        "StudySession", back_populates="quiz_sets", lazy="selectin"
    )
    user: Mapped["User"] = relationship("User", lazy="selectin")
    document: Mapped[Optional["Document"]] = relationship("Document", lazy="selectin")
    questions: Mapped[List["QuizQuestion"]] = relationship(
        "QuizQuestion", back_populates="quiz_set", cascade="all, delete-orphan", lazy="noload"
    )
    attempts: Mapped[List["QuizAttempt"]] = relationship(
        "QuizAttempt", back_populates="quiz_set", cascade="all, delete-orphan", lazy="noload"
    )
