resolver 127.0.0.11 ipv6=off;

server {
    listen 80;
    server_name amora-platform.se www.amora-platform.se;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
        access_log off;
        default_type text/plain;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name amora-platform.se www.amora-platform.se;

    ssl_certificate /etc/letsencrypt/live/amora-platform.se/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/amora-platform.se/privkey.pem;

    client_max_body_size 20M;

    location /api/ {
        set $backend_upstream http://backend:8000;
        proxy_pass $backend_upstream;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        set $frontend_upstream http://frontend:80;
        proxy_pass $frontend_upstream;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}